### ISSUE TITLE
The range of the rating (dependent variable) produced by the model is incorrect.

### ISSUE THREAD

**Issue by DaviesX** [DaviesX/movie-lens#1]
y = Dense(1, activation='tanh')(x)
The range of y is in (-1, 1), but the desired range is [0, 5].

**Comment by summerxyt** [comment]
After 4 or 5 years not touching git and github, I forgot the develop workflow...

Directly submitted to the repo.

**Comment by DaviesX** [comment]
Fixed at a3546a60
